# Workflow name displayed in the GitHub Actions UI
name: Lint Code

# Events that trigger the workflow
# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs define the tasks to be executed
jobs:
  lint:
    # Use the latest Ubuntu runner for the job
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code to the runner
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up the specified version of Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Enable npm caching to speed up installs
          cache-dependency-path: src/package-lock.json  # Specify the path for caching
      
      # Debug: List contents of src directory to verify package.json exists
      - name: Debug - List src directory contents
        run: ls -la src
      
      # Debug: Verify package.json contents
      - name: Debug - Show package.json
        run: cat src/package.json
      
      # Clear npm cache to avoid corrupted cache issues
      - name: Clear npm cache
        run: npm cache clean --force
      
      # Install all dependencies including devDependencies
      - name: Install dependencies
        run: cd src && npm install
      
      # Debug: Verify node_modules contents
      - name: Debug - Check node_modules
        run: ls -la src/node_modules | grep eslint-plugin-jest
      
      # Verify that eslint-plugin-jest is installed
      - name: Verify ESLint plugin installation
        run: cd src && npm list eslint-plugin-jest || echo "eslint-plugin-jest not found"
      
      # Explicitly install eslint-plugin-jest if not found
      - name: Install eslint-plugin-jest if missing
        run: cd src && npm install eslint-plugin-jest --save-dev
      
      # Run ESLint to lint the code
      - name: Run ESLint
        run: cd src && npx eslint .