# Workflow name displayed in the GitHub Actions UI
name: Lint Code

# Events that trigger the workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs define the tasks to be executed
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # Ensure devDependencies are installed
      - name: Install dependencies
        run: cd src && npm install --save-dev
      
      - name: Run ESLint
        run: cd src && npx eslint .